Import('env getObjects conf build subfolder getBinName getLibName')

env = env.Copy()
env.Append(LIBS = Split("""
	omfggui omfgconsole omfgloaders omfglua omfgblitters omfgutil glua loadpng""")
	)
	
#omfghttp

if conf == 'posix':
	env.Append(LIBS = Split("""
	        png12 z fmod
	        alleg-4.2.0 alleg_unsharable
	        zoidcom boost_filesystem-gcc boost_signals-gcc"""),
			LINKFLAGS = '-Wl,--export-dynamic'
		)
elif conf == 'mingw-cross':
	env.Append(LIBS = Split("""
	        png13 z fmod
	        alleg zoidcom_mw boost_filesystem-mgw boost_signals-mgw""")
		)
elif conf == 'basara':
	env.Append(LIBS = Split("""
	        png12 z fmod
	        alleg-4.2.0 alleg_unsharable
	        zoidcom boost_filesystem-gcc boost_signals-gcc"""),
	        LINKFLAGS = '-Wl,--export-dynamic'
		)
elif conf == 'darka':
	env.Append(LIBS = Split("""
	        png12 z fmod
	        alleg-4.2.0 alleg_unsharable
	        zoidcom boost_filesystem-gcc-mt boost_signals-gcc-mt"""),
	        LINKFLAGS = '-Wl,--export-dynamic'
		)
elif conf == 'lucas':
	env.Append(LIBS = Split("""
	        png12 z fmod-3.74.1
	        alleg-4.2.0 alleg_unsharable
	        zoidcom boost_filesystem-gcc boost_signals-gcc"""),
			LINKFLAGS = '-Wl,--export-dynamic'
		)
		
	        
# add more platforms here

SConscript([
	'./loaders/SConscript',
	'./lua/SConscript',
	#'./http/SConscript',
	'./blitters/SConscript'
	], exports = ['env', 'getObjects', 'getLibName', 'conf', 'build', 'subfolder'])

exename = 'gusanos'
if build == 'dedserv' or build == 'dedserv-debug':
	exename += '-ded'
env.Program(getBinName(exename), getObjects(env))
#env.Parser('test.h', 'test.pg')